### ISSUE TITLE
have some example about metadata?

### ISSUE THREAD

**Issue by lialzm** [stspec/pyspssio#2]
I try this is not work

```
df=pd.DataFrame({
	'a':[1,2,3]
})


pyspssio.write_sav('test.sav', df,{
'a':{
"label":"abc",
"varNames":[1,2]
	}
})
```

**Comment by stspec** [comment]
It might be easier to understand the metadata structure by reading an SPSS file first and inspecting the returned metadata dictionary.

```
import json
import pyspssio

df, meta = pyspssio.read_sav('spss_file.sav')

# json.dump or json.dumps meta
```
Variable names are solely determined by dataframe columns for now, so passing "varNames" to write_sav won't do anything.

Otherwise, you can pass metadata properties as a combined dictionary and/or separate kwargs. For example:

```
pyspssio.write_sav(
    'test.sav', 
    df, 
    metadata={'varLabels': {'a': 'abc'}, 'varFormats': {'a': 'F10'}}
)

# or

pyspssio.write_sav(
    'test.sav', 
    df, 
    varLabels={'a': 'abc'},
    varFormats={'a': 'F10'}
)
```

Note that starting with version 0.3.0 (not yet released), the metadata attribute names have been conformed to PEP8. So for example, `varLabels` will be called `var_labels` instead. `multRespDefs` will also be changed to just `mrsets`.
