### ISSUE TITLE
arm64 architecture not supported?

### ISSUE THREAD

**Issue by heijligers** [stspec/pyspssio#5]
`OSError: dlopen(/Users/datascience/PycharmProjects/Projects/P105089-Asics/venv/lib/python3.11/site-packages/pyspssio/spssio/macos/libspssdio.dylib, 0x0006): tried: '/Users/datascience/PycharmProjects/Projects/P105089-Asics/venv/lib/python3.11/site-packages/pyspssio/spssio/macos/libspssdio.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/datascience/PycharmProjects/Projects/P105089-Asics/venv/lib/python3.11/site-packages/pyspssio/spssio/macos/libspssdio.dylib' (no such file), '/Users/datascience/PycharmProjects/Projects/P105089-Asics/venv/lib/python3.11/site-packages/pyspssio/spssio/macos/libspssdio.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

**Comment by stspec** [comment]
This package uses the SPSS I/O module from here:
https://community.ibm.com/community/user/ai-datascience/viewdocument/extensions-tools-and-utilities-for

Those modules have separate binaries for:

- win64
- macos
- lin64
- plinux64
- zlinux64

Because of space limitations on PyPI, I only included the win64, macos, and lin64 binaries there. However, you can manually reference another binary anywhere on your machine by changing `pyspssio.config.spssio_module` to the filepath of your alternate binary.

If there's a compatible arm64 I/O module somewhere, please try that approach.

**Comment by heijligers** [comment]
Thanks for the tip!

I'll see how far I'll get and report back when I have made any progress

**Comment by arsoni20** [comment]
I am getting the same issue while accessing it in Macbook pro M1 chip. Any idea what we can do to make it work ?

**Comment by arsoni20** [comment]
I think there is no support for ARM64 from IBM :( 
<img width="238" alt="image" src="https://github.com/stspec/pyspssio/assets/43062020/cda43146-d80a-40d2-a31b-7da138c196da">
